# Generated by Django 3.1.7 on 2021-03-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={},
        ),
    ]
