# Generated by Django 3.1.7 on 2021-03-07 07:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210306_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='grade',
        ),
        migrations.AddField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='problemanswer',
            name='senttime',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2021, 3, 7, 11, 5, 18, 38751)),
        ),
    ]
