# Generated by Django 3.1.7 on 2021-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210306_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='grade',
        ),
    ]
