# Generated by Django 3.1.7 on 2021-03-07 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210307_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemanswer',
            name='grade',
        ),
        migrations.AlterField(
            model_name='problemanswer',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='problemanswer',
            name='senttime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 7, 11, 8, 45, 509081)),
        ),
    ]
