# Generated by Django 3.1.7 on 2021-03-07 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210307_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemanswer',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemanswer',
            name='senttime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 7, 11, 28, 57, 785680)),
        ),
    ]
