# Generated by Django 3.1.7 on 2021-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210307_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemanswer',
            name='senttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
