# Generated by Django 3.1.7 on 2021-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20210307_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(),
        ),
    ]
